### ISSUE TITLE
Improve zopfli header search

### ISSUE THREAD

**Issue by kmilos** [cgohlke/imagecodecs#10]
Some platforms put it at include/zopfli.h, while some at include/zopfli/zopfli.h

Rather than hard-coding zopfli/zopfli.h in [zopfli.pxd](https://github.com/cgohlke/imagecodecs/blob/a598eda814c01dc1deafb41297b21b016717970b/imagecodecs/zopfli.pxd#L7), might be better to remove the prefix and handle it instead in setup.py customize_build_* just like others (e.g. jxrlib).

**Comment by cgohlke** [comment]
I'll change this for the next release. It's annoying. The three biggest target platforms put the zopfli headers in a subdirectory.
