### ISSUE TITLE
NumPy 2.0 support

### ISSUE THREAD

**Issue by jakirkham** [cgohlke/imagecodecs#100]
NumPy 2.0 is coming out soon ( https://github.com/numpy/numpy/issues/24300 ). NumPy 2.0.0rc1 packages for conda & wheels came out 3 weeks back ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 )

To prepare for NumPy 2.0, it might be worthwhile to start testing against NumPy 2 in CI

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html )

If imagecodecs make use of NumPy's C API (and produces wheels that use it), having a release of imagecodecs with wheels built against NumPy 2.0.0rc1 would be helpful to ensure NumPy 1 & 2 compatible wheels (as wheels built against NumPy 1 won't be compatible with NumPy 2). More details in [this NumPy 2 ABI doc]( https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling )

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share imagecodecs current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

**Comment by jakirkham** [comment]
> If imagecodecs make use of NumPy's C API...

It looks like this may be the case based on lines like this

https://github.com/cgohlke/imagecodecs/blob/2ddadafd413c8b035b8f6339e8ea603bb416f011/imagecodecs/_shared.pyx#L44

**Comment by cgohlke** [comment]
I am aware of the numpy 2 transition. The development version of imagecodecs already passes all tests possible. For CI to succeed, some test dependencies such as numcodecs and blosc 1 need numpy 2 compatible releases. The next imagecodecs release is also waiting for updates of some dependencies: liblzma, Little-CMS...

**Comment by jakirkham** [comment]
Thanks Christoph! 🙏

Ok that's good to know

Took a look at Numcodecs in issue ( https://github.com/zarr-developers/numcodecs/issues/521 ). It only uses NumPy's Python API (and a very limited set at that), which was unaffected by the new version. Also ran tests locally for good measure. So think it should already work (though please let us know if you see issues)

With Blosc 1, it appears to [only use NumPy for testing]( https://github.com/Blosc/python-blosc/blob/715bc6fe44b15bc42f397b14b631f28f2e651ea2/setup.py#L93 ). Searching [the Blosc 1 code more generally]( https://github.com/search?q=repo%3ABlosc%2Fpython-blosc%20numpy&type=code ), it has some benchmarks and docs that use NumPy, but nothing else AFAICT. Is there somewhere else where NumPy comes up in Blosc 1?

Regarding the other dependencies, do these use NumPy as well (IOW are these Python wrappers of libraries) or are these just the C/C++ libraries?

**Comment by cgohlke** [comment]
You are right. Blosc 1 does not link to numpy (it was blosc2, which now has a numpy compatible release), neither does numcodecs (it was zfpy that failed, which is optional). Looks like imagecodecs should be good to build and test on CI then. I'll try on the weekend.

**Comment by jakirkham** [comment]
Ah ok. Good to know about Blosc 2

Also good catch with Numcodecs' optional zfpy. Appears to be tracked in upstream issue: https://github.com/LLNL/zfp/issues/210

**Comment by cgohlke** [comment]
Fixed in v2024.6.1.
