### ISSUE TITLE
Provide `libultrahdr` support

### ISSUE THREAD

**Issue by cmahnke** [cgohlke/imagecodecs#108]
It's a bit unfortunate that the README.md lists other libraries with image support. This can be a bit misleading if one googles for `libultrahdr` and `python`...
Anyways since I end up here that way, can you please consider adding `libultrahdr` support? Thanks!

**Comment by cgohlke** [comment]
`libultrahdr` is on the radar but the current 1.0 release has too many issues and no C API.

I don't see any issue with libultrahdr being listed at the end of the "Notes" section under "Other Python packages and C libraries providing imaging or compression codecs".

**Comment by cgohlke** [comment]
[libultrahdr 1.1.0](https://github.com/google/libultrahdr/releases/tag/1.1.0) is released. It improves building (CMake install still doesn't work) and has a [C compatible interface](https://github.com/google/libultrahdr/blob/main/ultrahdr_api.h).

**Comment by cmahnke** [comment]
@cgohlke : Thanks for the update - your radar is monitoring very closely.

I'm not sure what you mean with "CMake install still doesn't work" - can you elaborate a bit so I can add an issue (to `libultrahdr`) addressing this?

I assume you're not referring to a CMake option like `-DCMAKE_INSTALL_PREFIX=/usr` in combination with `make install` or if so, that there a potential problems with `pkg-config` for example.

**Comment by cgohlke** [comment]
> I assume you're not referring to a CMake option like -DCMAKE_INSTALL_PREFIX=/usr in combination with make install

Actually, that's what I was referring to. I haven't looked at it in detail at all, just noticed that my usual build scripts fail to install. Also, it is not a showstopper. The few header and library files can be copied individually.

**Comment by cgohlke** [comment]
[Install is disabled when building a static library](https://github.com/google/libultrahdr/blob/bddf8da6c21c9b5c67002ae8919bd9e7ebe5f475/CMakeLists.txt#L115-L124).

**Comment by cmahnke** [comment]
Ok, understood - is it a mandatory requirement?
I suppose a static library is needed for packaging, so this could also be done via the Python-based system, that build the module / wheel?

**Comment by cmahnke** [comment]
Maybe things get easier after this has been merged:
https://github.com/google/libultrahdr/pull/255

**Comment by cgohlke** [comment]
Unfortunately the libultrahdr encoder only accepts HDR content in `24bppYCbCrP010` and `32bppRGBA1010102` formats, not `64bppRGBAHalfFloat`. Not really useful for this package. Decoding to float16 works though.

**Comment by cgohlke** [comment]
See https://github.com/google/libultrahdr/discussions/143

**Comment by cgohlke** [comment]
See also https://github.com/google/libultrahdr/issues/268

**Comment by cmahnke** [comment]
Yes, currently the libraries main focus is on mobile development - I suspect that these quite esoteric formats are due to the outputs of mobile camera hardware, to avoid conversion steps. It's possible to convert them using `ffmpeg` but that would certainly a bit of overkill, like implementing your own conversions.

**Comment by cgohlke** [comment]
I have implemented the ultrahdr codec. Is there any specific functionality you had in mind? The encoder is sort of useless right now since it does not support float16 input, only packed RGBA1010102. That also complicates testing since most tests are based on roundtrips with (unpacked) numpy arrays...

**Comment by cmahnke** [comment]
I was needing it for image tiling and scaling (including combinations of both) - currently I helped myself with doing those steps on a SDR Image and enhancing the results with the `ultrahdr_app`.

**Comment by cgohlke** [comment]
Another roadblock:
```Python-traceback
imagecodecs._ultrahdr.UltrahdrError: uhdr_enc_set_raw_image returned 'image dimensions cannot be odd, received image dimensions 31x32'
```

**Comment by cmahnke** [comment]
@cgohlke: https://github.com/google/libultrahdr/issues/270 has been closed as fixed - but one question still remains from the author regarding formats, I guess I need your opinion on how to proceed. Is the change all you need?

**Comment by cgohlke** [comment]
Yes, I just tried 1.2.0 and encoding images with uneven dimensions works now (using RGBA1010102 image with gainmap_scale_factor=1). For this library, I'm only interested in linear RGBA half float images. The `ultrahdr_encode` function is not really useful yet...

**Comment by cgohlke** [comment]
Imagecodecs 2024.9.22 adds a preliminary Ultra HDR codec based on libultrahdr 1.2.0.

**Comment by cgohlke** [comment]
Encoding linear rgbaf16 was added in https://github.com/ittiam-systems/libultrahdr/commit/613fee15db6cfae17eee16c77601bf38d24c7537 but requires a fix in imagecodecs to work:

```diff
diff --git a/imagecodecs/_ultrahdr.pyx b/imagecodecs/_ultrahdr.pyx
index e29884a..cabbe0e 100644
--- a/imagecodecs/_ultrahdr.pyx
+++ b/imagecodecs/_ultrahdr.pyx
@@ -158,19 +158,16 @@ def ultrahdr_encode(
     memset(&raw_image, 0, sizeof(uhdr_raw_image_t))
     raw_image.h = <int> src.shape[0]
     raw_image.w = <int> src.shape[1]
+    raw_image.range = UHDR_CR_FULL_RANGE
     raw_image.planes[UHDR_PLANE_PACKED] = <void *> src.data
+    raw_image.stride[UHDR_PLANE_PACKED] = <unsigned int> src.shape[1]

     if src.ndim == 2:
         raw_image.fmt = UHDR_IMG_FMT_32bppRGBA1010102
         raw_image.ct = UHDR_CT_HLG
-        raw_image.range = UHDR_CR_FULL_RANGE
-        raw_image.stride[UHDR_PLANE_PACKED] = <unsigned int> src.shape[1]
     else:
         raw_image.fmt = UHDR_IMG_FMT_64bppRGBAHalfFloat
         raw_image.ct = UHDR_CT_LINEAR
-        raw_image.stride[UHDR_PLANE_PACKED] = <unsigned int> (
-            src.shape[1] * src.shape[2]
-        )

     if gamut is not None:
         raw_image.cg = gamut
```

![rgba](https://github.com/user-attachments/assets/1ab9264c-7955-4c3f-baf9-04ea902a1a15)
