### ISSUE TITLE
could not import name 'jpeg8_encode' from 'imagecodecs'" after packaging Django project with PyInstaller

### ISSUE THREAD

**Issue by Songhao-LI** [cgohlke/imagecodecs#109]
Dear author

I am using tiffslide for my Django project. Every function works well when I run my code directly. But when I create a package with PyInstaller, running the package .exe throws the following error:

"could not import name 'jpeg8_encode' from 'imagecodecs'" when using PyInstaller

I tried specifying a hidden import like this::
![image](https://github.com/user-attachments/assets/7de0db3d-8c1a-45e0-b01c-4b11d8c7bd49)
And I also found the dist directory imagecodecs folder has only 3 file _shared.cp39-win_amd64.pyd, zlib.cp39-win_amd64.pyd to imagecodecs folder of dist

But it didn't work either. Could you fix the problem?

my env:
windows 11 64bit
Python 3.9.19
tifffile==2024.8.30
tiffslide==2.4.0
imagecodecs==2024.6.1

**Comment by cgohlke** [comment]
The `hiddenimports = ...` line looks wrong (extra underscore). Try:
```Python
hiddenimports = ["imagecodecs." + x for x in imagecodecs._extensions()] + ["imagecodecs._shared"]
```
Or try add the `_jpeg8*.pyd`, `_jpeg2k*.pyd`, and `_imcd*.pyd` files to `datas`
