### ISSUE TITLE
pyinstaller package throw error "could not import name 'zlib_encode' from 'imagecodecs'"

### ISSUE THREAD

**Issue by hbh112233abc** [cgohlke/imagecodecs#11]
Dear author

I make a program create tiff use `tifffile`, when I create package with pyinstaller,run the package exe throw an error
```
 could not import name 'zlib_encode' from 'imagecodecs'
```
I found the dist directory `imagecodecs` folder only has one file `_shared.cp37-win_amd64.pyd`, copy `_zlib.cp37-win_amd64.pyd` to `imagecodecs` folder of dist, above error not throw! 

could you fix the problem?

my env:
windows 10 64bit
python 3.7 64bit
tifffile 2021.1.14
imagecodecs 2021.1.11

**Comment by cgohlke** [comment]
Try to specify [hidden-import](https://pyinstaller.readthedocs.io/en/stable/usage.html?highlight=hidden-import#what-to-bundle-where-to-search)

**Comment by Czaki** [comment]
In my case, this solve my problem:
https://github.com/4DNucleome/PartSeg/blob/c6a3810cbd77f008f7e9a1241632972145485823/launcher.spec#L36-L37 
https://github.com/4DNucleome/PartSeg/blob/c6a3810cbd77f008f7e9a1241632972145485823/launcher.spec#L77

**Comment by hbh112233abc** [comment]
> In my case, this solve my problem:
> https://github.com/4DNucleome/PartSeg/blob/c6a3810cbd77f008f7e9a1241632972145485823/launcher.spec#L36-L37
> https://github.com/4DNucleome/PartSeg/blob/c6a3810cbd77f008f7e9a1241632972145485823/launcher.spec#L77

em,I copy the file `_zlib.cp37-win_amd64.pyd` to my program folder,and set `.spec` append datas like:
```
datas = [
  ('_zlib.cp37-win_amd64.pyd','imagecodecs'),
]
```
then package folder `imagecodecs` will has `_zlib.cp37-win_amd64.pyd`, the problem is fixed!
