### ISSUE TITLE
Use Python library for Pcodec

### ISSUE THREAD

**Issue by mwlon** [cgohlke/imagecodecs#115]
Hey, just want to point out that Pcodec has a well-featured Python library that would probably work better than the C API imagecodecs currently uses. Online documentation is missing, but you can `help(...)` or generate the docs to see the API.

https://pypi.org/project/pcodec/

**Comment by cgohlke** [comment]
Hi. Thanks for your work on Pcodec!

> just want to point out that Pcodec has a well-featured Python library that would probably work better than the C API

I am of course aware of the Pcodec Python bindings (even providing some [unofficial win_arm64 builds](https://github.com/cgohlke/win_arm64-wheels)). However, one of the objectives of this project is not to depend on any Python packages except numpy.

> Online documentation is missing, but you can help(...) or generate the docs to see the API.

That's OK with me. And much better than this project, which doesn't have any docs :)

**Comment by mwlon** [comment]
I see, but I'm curious why not depend on other Python projects? The Pcodec pip package is basically just a dynamic library file, and if your users happen to depend on Pcodec through some other way, wouldn't it be better to share the same library? I suppose it would also work if everyone has the dynamic library on their system path, but for Python I think most people prefer their dlls as flexible per-env dependencies.

In any case, glad you're enjoying Pcodec, and feel free to close this issue if you're confident in the direction. And I know our C API example could use improvement, so feedback/contributions are certainly welcome.

**Comment by Skielex** [comment]
Given the usually wide scope of the project, I think avoiding having a lot of Python package dependencies actually makes good sense as it helps avoid mismatched versions and compatibility issues.

As, @mwlon mentioned the C interface could use some improvements. For instance, the use of `unsigned int` for size limits the size of the encoded data for no reason. I'll try to get this fixed.

**Comment by Skielex** [comment]
@cgohlke , I've created a PR correcting the data length type to `size_t` in the pcodec C-binding.
https://github.com/mwlon/pcodec/pull/235

Once again, nice work on this package.
