### ISSUE TITLE
JPEG2K: Support for multi tile, multi quality layers

### ISSUE THREAD

**Issue by cwognum** [cgohlke/imagecodecs#118]
Thank you for the awesome work you're doing by maintaining this library! I really like how it readily integrates with `numcodecs`, and by extension with `zarr`. 

I was wondering if adding support for _multiple tiles_ and for _multiple quality layers_ in JPEG2K is still on the roadmap. I noticed [this comment](https://github.com/cgohlke/imagecodecs/blob/50bac419858de471b934943f949835aad18b5a96/imagecodecs/_jpeg2k.pyx#L112) in the source code. 

I'm currently saving my image using [Pillow](https://github.com/python-pillow/Pillow).

```py
im.save(
    buffer,
    format="jpeg2000",
    quality_mode="rates",
    quality_layers=[80, 40, 20],
    irreversible=True,
    num_resolutions=8,
    precinct_size=(128, 128),
    codeblock_size=(64, 64),
)   
```

For my specific use case, this results in a compression ratio of ~19.6. It works, but requires some boiler plate code to register it as a codec with Zarr. This also implies we're pulling in a big dependency that can do a lot more than just encoding and decoding images.

Using `imagecodecs` instead, I get to a compression ratio of ~8.3. 

I would offer my help, but am not at all familiar with image codecs. My C is also a bit rusty, to say the least.

**Comment by cgohlke** [comment]
Hi @cwognum ,

can you provide an example image and code to reproduce your finding with current versions of Pillow and imagecodecs? How did you compare the image qualities? How/why would multiple tiles and quality layers improve compression efficiency or be useful in the context of Zarr/TIFF chunks?

**Comment by cwognum** [comment]
Hi @cgohlke , thanks for getting back to me so quickly. 

The dataset I'm working with is sourced from [here](https://huggingface.co/datasets/recursionpharma/rxrx3-core). I've attached an example image. 

<details><summary>Example here</summary>
<p>

![159548 0 0 0 Large](https://github.com/user-attachments/assets/d3818016-28bf-4cf4-8f00-f81875d32523)

</p>
</details> 

As you can see, there is a lot that can be compressed! 😅 

Here is an (possibly very naive) example: 
```py
import fsspec

import numpy as np

from io import BytesIO
from PIL import Image
from imagecodecs import jpeg2k_encode

with fsspec.open("https://github.com/user-attachments/assets/d3818016-28bf-4cf4-8f00-f81875d32523") as fp:
    im = Image.open(fp)

    # Save using Pillow
    buffer = BytesIO()
    
    im.save(
        buffer,
        format="jpeg2000",
        quality_mode="rates",
        quality_layers=[80, 40, 20],
        irreversible=True,
        num_resolutions=8,
        precinct_size=(128, 128),
        codeblock_size=(64, 64),
    )

    n_bytes_pillow = len(buffer.getvalue())
    print("No. bytes with PIL:", n_bytes_pillow)

arr = np.array(im)

n_bytes_imagecodec = len(jpeg2k_encode(arr))
print("No. bytes with Image Codecs:", n_bytes_imagecodec)
```

This will print: 
```
No. bytes with PIL: 13122
No. bytes with Image Codecs: 52777
```

**Comment by cgohlke** [comment]
`jpeg2k_encode(arr)` uses lossless compression by default. To get approximately the same peak signal to noise ratio as the Pillow method, use `jpeg2k_encode(arr, level=54)` (54 is the psnr). The compression ratios will be about the same, probably slightly better for imagecodecs.

I think that multi-tile, multi-quality-layers are superfluous for JPEG 2000 compressed Zarr chunks. 

> This also implies we're pulling in a big dependency

To be fair, imagecodecs is a bigger and less well supported dependency than Pillow.

**Comment by cwognum** [comment]
Thanks for the prompt reply. I figured I would be doing something wrong here... Thank you for bearing with me! I'll close the issue!
