### ISSUE TITLE
JPEG-LS near-lossless doesn't allow error bounds greater than 9

### ISSUE THREAD

**Issue by Messier-16** [cgohlke/imagecodecs#119]
Especially when compressing uint16 images, it is important for me to be able to allow an error bound of more than 9, but for some reason, line 92 in `_jpegls.pyx` restricts the max value to 9: `int32_t near_lossless = _default_value(level, 0, 0, 9)`

**Comment by cgohlke** [comment]
Thank you for reporting the issue. The upper limit will be removed in the next version.
