### ISSUE TITLE
Error when build from source

### ISSUE THREAD

**Issue by vanchung1995** [cgohlke/imagecodecs#23]
I tried to build from source instead of run pip install (I used python setup.py install). But it failed and I don't know what to do
My pip version is  21.2.4  from python 3.8

![Screenshot from 2021-09-07 12-32-59](https://user-images.githubusercontent.com/15941200/132289633-a74fa91f-396a-4071-8940-25a4743a719c.png)

**Comment by cgohlke** [comment]
You are not building against Python 3.8 but 3.6, which is no longer supported. There are some notes regarding the requirements for building from source. The wheel build scripts are in a [separate repo](https://github.com/Czaki/imagecodecs_build).

https://github.com/cgohlke/imagecodecs/blob/8eec683f117b44c178785f542831f530511608ff/imagecodecs/imagecodecs.py#L58-L115

https://github.com/cgohlke/imagecodecs/blob/8eec683f117b44c178785f542831f530511608ff/imagecodecs/imagecodecs.py#L162-L186
