### ISSUE TITLE
Where can I get the usage of  this package

### ISSUE THREAD

**Issue by TruePluto** [cgohlke/imagecodecs#27]
I want to read some lossless JPEG images with SOF3 via Python ， but I can't find any usage！I'll be appricaite if somebody give me a address or some code as a example。

**Comment by cgohlke** [comment]
Try:
```Python
import imagecodecs

with open('lossless.jpg', 'rb') as fh:
    encoded = fh.read()

image = imagecodecs.jpegsof3_decode(encoded)
# or
image = imagecodecs.ljpeg_decode(encoded)
```

**Comment by TruePluto** [comment]
It's work perfectly! Thank you very much.

**Comment by alirezadizaji** [comment]
Hi,
I have tried the same code for an image with .LJPEG file, however its decompression didn't go well. could you guide me for this?

**Comment by cgohlke** [comment]
Can't reproduce using a few random LJPEG files from DDSM.

Please be more specific. Which file? Which codec? What is the traceback, if any? 

The codecs are based on 3rd party libraries [jpg_0XC3.cpp](https://github.com/rordenlab/dcm2niix/blob/master/console/jpg_0XC3.cpp) and [liblj92](https://bitbucket.org/baldand/mlrawviewer/src/master/liblj92/). They are basically unmaintained.

[libjpeg](https://github.com/thorfdbg/libjpeg) is probably the best maintained library for decoding LJPEG. It is GPL licensed and therefore can't be used by imagecodecs. There's a Python wrapper at [pylibjpeg](https://github.com/pydicom/pylibjpeg-libjpeg).

**Comment by alirezadizaji** [comment]
I have used the following code:
`
from imagecodecs import ljpeg_decode
import imageio

with open(img_path, 'rb') as f:
        data = f.read()
        img = ljpeg_decode(data)
        imageio.imwrite(..., img)`

the input data comes from [this link](http://www.eng.usf.edu/cvprg/Mammography/DDSM/thumbnails/cancers/cancer_08/case1465/A-1465-1.html) (RIGHT_MLO), the saved image is as [this link](https://drive.google.com/file/d/1Uq9yD6LL85j3D88yR-sgjbEtc8F5FYJR/view?usp=sharing)

**Comment by cgohlke** [comment]
All software and libraries I tried return the same image data. If you think they are all wrong, try the original software provided by USF at http://www.eng.usf.edu/cvprg/Mammography/software/heathusf_v1.1.0.html.
