### ISSUE TITLE
Consider changing the way `option_lossess` is set in `jpegxl_encode`?

### ISSUE THREAD

**Issue by JackKelly** [cgohlke/imagecodecs#30]
Thanks again for all your work on imagecodecs!

In `jpegxl_encode`, `option_lossless` is set to True if `level is None or level < 0` ([line 160 of _jpegxl.pyx](https://github.com/cgohlke/imagecodecs/blob/master/imagecodecs/_jpegxl.pyx#L160)).

The `level` argument to `jpegxl_encode` is passed to [`JxlEncoderOptionsSetDecodingSpeed`](https://github.com/libjxl/libjxl/blob/v0.6.1/lib/include/jxl/encode.h#L317) which sets the **decoding** speed, not whether the image is lossless or not :slightly_smiling_face:.  That is, `level` is somewhat orthogonal to whether `lossless` mode should be engaged or not.

An improvement might be to set `option_lossless` to True if `distance` is `0.0`.  (See [the docs for distance](https://github.com/libjxl/libjxl/blob/v0.6.1/lib/include/jxl/encode.h#L333-L350))

(Also, would it be worth considering renaming `level` to `decoding_speed` or something like that?)

**Comment by cgohlke** [comment]
Right. This is mostly fixed in the development version, which introduces two additional parameters `lossless`, and `decodingspeed`
```
        JXL_BOOL option_lossless = lossless is None or bool(lossless)
        int option_tier = _default_value(decodingspeed, 0, 0, 4)
```

The `level` parameter is actually part of the imagecodecs encode API. Right now it is mapped to `lossless` and `tier` but maybe it's better mapped to `effort` or `distance`...

**Comment by JackKelly** [comment]
Awesome, thank you! Sorry for the silly question but how do I access the dev version of imagecodecs?

> The level parameter is actually part of the imagecodecs encode API. Right now it is mapped to lossless and tier but maybe it's better mapped to effort or distance...

As you probably know, [the `cjxl` utility has a `quality` setting](https://www.mankier.com/1/cjxl) (which takes a value between -inf and 100, where 100 is lossless).  If the `level` param in the `imagecodecs` API is supposed to take a value up to 100 then maybe it's worth checking the `cjxl` code to see how it maps from `quality` to `distance` etc?

**Comment by cgohlke** [comment]
AFAICT, the cjxl quality setting maps to fields in a private C++ struct. Those can't be set from C using the public API.
