### ISSUE TITLE
Can `jpegxl_decode` decode multiple frames?

### ISSUE THREAD

**Issue by JackKelly** [cgohlke/imagecodecs#32]
Thanks again for all your work on `imagecodecs`!

Can [`jpegxl_decode`](https://github.com/cgohlke/imagecodecs/blob/v2021.11.20/imagecodecs/_jpegxl.pyx#L424) decode multiple frames?

If I've understood correctly, `jpegxl_encode` can _encode_ multiple frames (in [this loop](https://github.com/cgohlke/imagecodecs/blob/v2021.11.20/imagecodecs/_jpegxl.pyx#L359-L400)). But I don't think `jpegxl_decode` can decode multiple frames yet? Or have I missed something? :slightly_smiling_face:

**Comment by cgohlke** [comment]
It's on the TODO list:

https://github.com/cgohlke/imagecodecs/blob/ddddb7bb0e34aa243e1b45c04b545343c0569828/imagecodecs/_jpegxl.pyx#L517

There seem to be no API to obtain the number of frames other than decoding all frames and counting...

**Comment by JackKelly** [comment]
Cool, thank you!

> There seem to be no API to obtain the number of frames other than decoding all frames

To be honest, that's fine for me. For my use-case, I'll always want to decode all the frames. So it would be great to be able to get all the frames back in one call to `imagecodecs`.

Thanks again for all your work on this!

**Comment by cgohlke** [comment]
For reference: [Questions about animated sequences](https://gitlab.com/wg1/jpeg-xl/-/issues/113).

**Comment by cgohlke** [comment]
I got the decoding of JXL animations working with libjxl 0.6. The necessary API for encoding animations will be available in the next major release of libjxl (https://github.com/libjxl/libjxl/pull/909).

**Comment by JackKelly** [comment]
Oooh, that's super-cool, thank you!
