### ISSUE TITLE
Feature Request: HEVC/H.265 Support

### ISSUE THREAD

**Issue by John-P** [cgohlke/imagecodecs#33]
It would be nice to have support for other HEIF codecs in addition to the AVIF support that is already in place. I see that there are a few libraries which may be useful for this:

- [libde265](https://github.com/strukturag/libde265)
- [libheif](https://github.com/strukturag/libheif) which uses libde265
- ffmpeg (which is using a fork of libde265)

I have also been trying to figure out if these would also work with hardware acceleration, e.g. with Intel CPUs, but I am a little unclear on this. There is some useful information on the Arch wiki here https://wiki.archlinux.org/title/Hardware_video_acceleration.

Thank you for putting together this package. It's been incredibly useful.

**Comment by cgohlke** [comment]
HEIF is on the horizon:

https://github.com/cgohlke/imagecodecs/blob/92a8620ac300fbeb77929cfa72bf78fd74584345/imagecodecs/imagecodecs.py#L449

https://github.com/cgohlke/imagecodecs/blob/92a8620ac300fbeb77929cfa72bf78fd74584345/setup.py#L153

I am trying to avoid LGPL licensed dependencies, which prevent to distribute static builds. I have not seen much use/traction of HEIF in other container formats (TIFF, zarr) and scientific imaging when compared to for example JPEG XL. What is your use case?

**Comment by John-P** [comment]
Thanks, that's great. I am interested in experimenting with use in TIFF or zarr. I find AVIF quite slow to encode, at least on my machines, and was interested in HEVC as I have read that the support for hardware acceleration is better.

**Comment by John-P** [comment]
On the plus side, it looks like the libde265 library is LGPGL. It may also be useful to have the intra-frame coding alone without the HEIF wrapper.

**Comment by John-P** [comment]
Ah yes it does appear to be decode only, that is unfortunate. I did also stumble across this library with is BSD licensed https://github.com/ultravideo/kvazaar but I am also unsure of the patent and licensing issues.

**Comment by John-P** [comment]
RE patents. It looks like royalties are paid based on the devices sold to end users with the first 100,000 devices/year paying no royalty for essential patents. Not sure how that works of a software package though. There is a summary here: https://www.mpegla.com/wp-content/uploads/HEVCweb.pdf

**Comment by cgohlke** [comment]
More discouraging news besides patents and GPL:

* it seems `x265` can be compiled for either 8-bit or 10-bit but not both -> heif_encode can either handle uint8 or uint16 input. Workaround is to provide two codecs, heif8 and heif10.
* `libheif` does not support sequences/tracks or bursts, only top level images -> no inter-frame coding.

I'll probably include the heif codec source code with the next release, but not provide binaries or further support unless something fundamentally improves.

**Comment by John-P** [comment]
Thanks for the update. That is a shame. Happy to test out using the codec from source if you need a guinnea pig though.

**Comment by cgohlke** [comment]
A HEIF codec (source code only) is in v2022.7.27.
