### ISSUE TITLE
Did the source drop support for 3.7?

### ISSUE THREAD

**Issue by hmaarrfk** [cgohlke/imagecodecs#34]
It seems that the pypi package now requires python 3.8

That is fair, I understand the maintenance burden can be large.

Did the source actually drop support for 3.7? I'm trying to get the pacakge working on conda-forge and I would prefer to release a package for 3.7 if i can.

nep29, suggests that we might keep it for an other 6 months. Let me know
https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

**Comment by cgohlke** [comment]
I don't think there are any changes in the source beside `python_requires='>=3.8',` that prevent you from still using Python 3.7.

> nep29, suggests that we might keep it for an other 6 months

I was following the [Drop Schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule):

`On Dec 26, 2021 drop support for Python 3.7 (initially released on Jun 27, 2018)`
