### ISSUE TITLE
zfp 1.0

### ISSUE THREAD

**Issue by hmaarrfk** [cgohlke/imagecodecs#45]
Just flagging this here. zfp just released their 1.0 system and it seems like they moved some headers around causing builds to fail

https://github.com/conda-forge/imagecodecs-feedstock/pull/62

I think you want to change  `bitstream.h` to `zfp/bitstream.h` but I haven't studied change (if any) to the API orthe underlying structures.

**Comment by cgohlke** [comment]
Fixed in v2022.8.8.

**Comment by hmaarrfk** [comment]
Thank you for the quick resolution!
