### ISSUE TITLE
Build failure for c-blosc2 2.3.x

### ISSUE THREAD

**Issue by kmilos** [cgohlke/imagecodecs#47]
See https://github.com/msys2/MINGW-packages/pull/13206/checks#step:10:18022

Can be worked around by turning off this particular error in both GCC and Clang, but should ideally be fixed.

**Comment by cgohlke** [comment]
This is already fixed in the development version. The next version of imagecodecs will require libjxl 0.7 and c-blosc 2.4.

**Comment by kmilos** [comment]
Ok, thanks

**Comment by MehdiChinoune** [comment]
> This is already fixed in the development version. The next version of imagecodecs will require libjxl 0.7 and c-blosc 2.4.

I couldn't find any development version.
This repo has only one branch that hasn't changed since the latest release.

**Comment by cgohlke** [comment]
Fixed in v2022.12.22.
