### ISSUE TITLE
install via pip on M1 fails due to wrong include dir for openjpeg

### ISSUE THREAD

**Issue by StefanBaar** [cgohlke/imagecodecs#49]
I am trying to install imagecodecs via pip (from pyenv) on M1 with the following command:

`pip install --global-option=build_ext --global-option="-I/opt/homebrew/include/" --global-option="-L/opt/homebrew/lib" -U imagecodecs`

Even though, I specify the include dir, pip can't find the openjpeg.h (which is present in /opt/homebrew/include/openjpeg-2.5/ )

The output looks something like this:

```
      building 'imagecodecs._jpeg2k' extension
      creating build/temp.macosx-12.6-arm64-3.9/3rdparty/openjpeg
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -Iimagecodecs -I3rdparty/openjpeg -I/usr/include/openjpeg-2.3 -I/usr/include/openjpeg-2.4 -I/usr/include/openjpeg-2.5 -I/opt/homebrew/include/ -I/Users/unknownms/.pyenv/versions/3.9-dev/include/python3.9 -I/Users/unknownms/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/numpy/core/include -c 3rdparty/openjpeg/color.c -o build/temp.macosx-12.6-arm64-3.9/3rdparty/openjpeg/color.o
      3rdparty/openjpeg/color.c:45:10: fatal error: 'openjpeg.h' file not found
      #include "openjpeg.h"
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> imagecodecs

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

what am I missing?

**Comment by cgohlke** [comment]
Try to also add `--global-option="-I/opt/homebrew/include/openjpeg-2.5/` or wherever homebrew keeps `openjpeg.h`.

**Comment by StefanBaar** [comment]
thank you very much, using multiple include dirs worked. 

Like this:

`pip install --global-option=build_ext --global-option="-I/opt/homebrew/include/:/opt/homebrew/include/openjpeg-2.5/" --global-option="-L/opt/homebrew/lib" -U imagecodecs`

**Comment by anntzer** [comment]
@cgohlke I note that you already have at https://github.com/cgohlke/imagecodecs/blob/95688564dc8312ad81ea082fe7404a537fb2ded9/setup.py#L239-L247 a cutout so that the headers are found if they are under /usr/include/openjpeg-2.X/, but the problem here is that the prefix is not /usr (and thus the headers in /usr/include) but /opt/homebrew (and thus the headers in /opt/homebrew/include).
Would you consider a patch that makes this configurable e.g. with a $PREFIX environment variable (name up to bikeshedding)?  Note that this would help not only for openjpeg, but also for jxrlib.
If yes I can have a try at it.

**Comment by cgohlke** [comment]
How about defining a `customize_build_homebrew` function and detect homebrew (e.g., `if os.path.exists('/usr/homebrew'): ...`), similar to macports:

https://github.com/cgohlke/imagecodecs/blob/95688564dc8312ad81ea082fe7404a537fb2ded9/setup.py#L535-L566

https://github.com/cgohlke/imagecodecs/blob/95688564dc8312ad81ea082fe7404a537fb2ded9/setup.py#L608-L609

**Comment by anntzer** [comment]
If you are willing to have such a special-casing, certainly that works too (the prefix is /opt/homebrew (or rather `$(brew --prefix)`), though).

**Comment by kylebarron** [comment]
`brew --prefix` is best because brew puts libraries in a different place depending whether the installation is on intel or ARM macs
