### ISSUE TITLE
ljpeg (lj92.c) ge bug with example file

### ISSUE THREAD

**Issue by tgeorge11** [cgohlke/imagecodecs#61]
I have been working on trying to decode some ljpeg images from here
http://www.eng.usf.edu/cvprg/mammography/database.html

I spent some time with gdcm and your library with not much luck.
I have run their binary in linux and it decodes their files ok, it seems its an old a rare bug, but older medical scans seem to have it.
I feel that my skill set is not up to patching and compiling.
Unfortunately I am more comfortable in windows with precompiled 

That being said, I think the key may be ~ line 555 of lj92.c or ~ line 560? of jpegsof3.cpp
decoding with jpegsof3_decode or ljpeg_decode both give same bad graduated pattern

Sample file with the pvrg patch they found
[stanford.pvrg.jpeg.ge_solaris_combo.patch.zip](https://github.com/cgohlke/imagecodecs/files/10420711/stanford.pvrg.jpeg.ge_solaris_combo.patch.zip)
[test1-ljpeg.zip](https://github.com/cgohlke/imagecodecs/files/10420713/test1-ljpeg.zip)

**Comment by cgohlke** [comment]
All libraries I have tried decode the test1.ljpeg file with the same result. If gdcm is able to detect and work around the buggy ljpeg files, try the gdcm Python bindings or Windows binaries:

https://pypi.org/project/gdcm/#files
https://github.com/malaterre/GDCM/releases

**Comment by cgohlke** [comment]
I might have misunderstood: by "their binary", did you mean `PVRG` plus patches or "GDCM"? 

I was able to build the PVRG `jpeg` binary in Windows WSL and successfully convert the test1 file. It also compiles to native Windows executable with the Mingw/UCRT compiler, but the executable does not work correctly.

**Comment by cgohlke** [comment]
See also #27.

According to https://deckard.duhs.duke.edu/ddsm_sql/c17.html, these LJPEG files can only be decoded by the software that generated them:

> LJPEG Files
> 
> The *.LJPEG files contain the image data. The files are compressed using the Lossless JPEG compression software developed at Stanford University. This software is notoriously and tragically flawed. Once an image is compressed using it, it may only be uncompressed using the same software. Other Lossless JPEG software is unable to undo the confusion caused by the Stanford code, but at least the Stanford code can undo itself. To further compound this, when each image was compressed, the row and column input parameters to the compressor were systematically reversed. This means that once you decompress a DDSM image with the Stanford software, it will report the rows and columns of the image reversed. However, the image data contained in the *ics files is correct.

There's a Linux port of the original DDSM USF lossless JPEG compression program, `JPEGv1.2.1_LINUXport.tgz`, still available on the [WaybackMachine](https://web.archive.org/web/20170604105845/http://www.cs.unibo.it/~roffilli/sw.html#DDSMUSF). It compiles and works without changes on WSL.

**Comment by tgeorge11** [comment]
Thank you for all your help.
I was working in this direction but my windows machine will not install wsl
(some other cryptic error)
I had been working for the last 2 weeks on this with little progress.
Your clues helped me yesterday.
I had some success in msys2
I lost another day trying to understand performance and why i could not
compile in clang.

I am over the hump, and have been making good progress today.

Thanks again for your help and clues (the compiling on windows)
I got a binary working in windows, and python is happy (as I)

I am working on a cancer project, and it seems this database has the best
'marked' cancers (outlines)

Regards
Trent
