### ISSUE TITLE
imagecodecs 2023.3.16 build error: unknown type name 'J12SAMPROW'

### ISSUE THREAD

**Issue by Schamschula** [cgohlke/imagecodecs#65]
While attempting to update the py-imagecodecs Portfile to version 2023.3.16 under MacPorts, I ran into the following build error:

> /usr/bin/clang -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch arm64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Iimagecodecs -I/opt/local/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -I/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/include -c imagecodecs/_jpeg8.c -o build/temp.macosx-12.0-arm64-cpython-311/imagecodecs/_jpeg8.o
> In file included from imagecodecs/_jpeg8.c:746:
> In file included from /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5:
> In file included from /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
> In file included from /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1940:
> /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
> #warning "Using deprecated NumPy API, disable it with " \
>  ^
> imagecodecs/_jpeg8.c:3843:3: error: unknown type name 'J12SAMPROW'; did you mean 'JSAMPROW'?
>   J12SAMPROW __pyx_v_rowpointer12;
>   ^~~~~~~~~~
>   JSAMPROW
> /opt/local/include/jpeglib.h:69:18: note: 'JSAMPROW' declared here
> typedef JSAMPLE *JSAMPROW;      /* ptr to one image row of pixel samples. */
>                  ^
> imagecodecs/_jpeg8.c:3844:3: error: unknown type name 'J16SAMPROW'; did you mean 'JSAMPROW'?
>   J16SAMPROW __pyx_v_rowpointer16;
>   ^~~~~~~~~~
>   JSAMPROW
> /opt/local/include/jpeglib.h:69:18: note: 'JSAMPROW' declared here
> typedef JSAMPLE *JSAMPROW;      /* ptr to one image row of pixel samples. */
>                  ^
> imagecodecs/_jpeg8.c:5434:11: error: implicit declaration of function 'jpeg_enable_lossless' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>           jpeg_enable_lossless((&__pyx_v_cinfo), __pyx_v_predictor_selection_value, 0);
>           ^
> imagecodecs/_jpeg8.c:5655:38: error: use of undeclared identifier 'J12SAMPROW'
>             __pyx_v_rowpointer12 = ((J12SAMPROW)(((char *)__pyx_v_src->data) + (__pyx_v_cinfo.next_scanline * __pyx_v_rowstride)));
>                                      ^
> imagecodecs/_jpeg8.c:5664:20: error: implicit declaration of function 'jpeg12_write_scanlines' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>             (void)(jpeg12_write_scanlines((&__pyx_v_cinfo), (&__pyx_v_rowpointer12), 1));
>                    ^
> imagecodecs/_jpeg8.c:5664:20: note: did you mean 'jpeg_write_scanlines'?
> /opt/local/include/jpeglib.h:953:20: note: 'jpeg_write_scanlines' declared here
> EXTERN(JDIMENSION) jpeg_write_scanlines(j_compress_ptr cinfo,
>                    ^
> imagecodecs/_jpeg8.c:5695:38: error: use of undeclared identifier 'J16SAMPROW'
>             __pyx_v_rowpointer16 = ((J16SAMPROW)(((char *)__pyx_v_src->data) + (__pyx_v_cinfo.next_scanline * __pyx_v_rowstride)));
>                                      ^
> imagecodecs/_jpeg8.c:5704:20: error: implicit declaration of function 'jpeg16_write_scanlines' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>             (void)(jpeg16_write_scanlines((&__pyx_v_cinfo), (&__pyx_v_rowpointer16), 1));
>                    ^
> imagecodecs/_jpeg8.c:5704:20: note: did you mean 'jpeg_write_scanlines'?
> /opt/local/include/jpeglib.h:953:20: note: 'jpeg_write_scanlines' declared here
> EXTERN(JDIMENSION) jpeg_write_scanlines(j_compress_ptr cinfo,
>                    ^
> imagecodecs/_jpeg8.c:6071:3: error: unknown type name 'J12SAMPROW'; did you mean 'JSAMPROW'?
>   J12SAMPROW __pyx_v_rowpointer12;
>   ^~~~~~~~~~
>   JSAMPROW
> /opt/local/include/jpeglib.h:69:18: note: 'JSAMPROW' declared here
> typedef JSAMPLE *JSAMPROW;      /* ptr to one image row of pixel samples. */
>                  ^
> imagecodecs/_jpeg8.c:6072:3: error: unknown type name 'J16SAMPROW'; did you mean 'JSAMPROW'?
>   J16SAMPROW __pyx_v_rowpointer16;
>   ^~~~~~~~~~
>   JSAMPROW
> /opt/local/include/jpeglib.h:69:18: note: 'JSAMPROW' declared here
> typedef JSAMPLE *JSAMPROW;      /* ptr to one image row of pixel samples. */
>                  ^
> imagecodecs/_jpeg8.c:7035:36: error: use of undeclared identifier 'J12SAMPROW'
>           __pyx_v_rowpointer12 = ((J12SAMPROW)__pyx_v_dst->data);
>                                    ^
> imagecodecs/_jpeg8.c:7055:20: error: implicit declaration of function 'jpeg12_read_scanlines' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>             (void)(jpeg12_read_scanlines((&__pyx_v_cinfo), (&__pyx_v_rowpointer12), 1));
>                    ^
> imagecodecs/_jpeg8.c:7055:20: note: did you mean 'jpeg_read_scanlines'?
> /opt/local/include/jpeglib.h:998:20: note: 'jpeg_read_scanlines' declared here
> EXTERN(JDIMENSION) jpeg_read_scanlines(j_decompress_ptr cinfo,
>                    ^
> imagecodecs/_jpeg8.c:7085:36: error: use of undeclared identifier 'J16SAMPROW'
>           __pyx_v_rowpointer16 = ((J16SAMPROW)__pyx_v_dst->data);
>                                    ^
> imagecodecs/_jpeg8.c:7105:20: error: implicit declaration of function 'jpeg16_read_scanlines' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>             (void)(jpeg16_read_scanlines((&__pyx_v_cinfo), (&__pyx_v_rowpointer16), 1));
>                    ^
> imagecodecs/_jpeg8.c:7105:20: note: did you mean 'jpeg_read_scanlines'?
> /opt/local/include/jpeglib.h:998:20: note: 'jpeg_read_scanlines' declared here
> EXTERN(JDIMENSION) jpeg_read_scanlines(j_decompress_ptr cinfo,
>                    ^
> 1 warning and 13 errors generated.
> error: command '/usr/bin/clang' failed with exit code 1
> 
> ERROR Backend subprocess exited when trying to invoke build_wheel

**Comment by cgohlke** [comment]
Imagecodecs 2023.3.16 requires libjpeg-turbo 3, which is currently in beta:

https://github.com/cgohlke/imagecodecs/blob/v2023.3.16/imagecodecs/imagecodecs.py#L164

**Comment by Schamschula** [comment]
This is unfortunate, as libjpeg-turbo 3 breaks core graphics programs like `GraphicsMagick` and `ImageMagick`. On MacPorts we'll have to roll back the supported version of `py-imagecodecs`.

See: https://github.com/macports/macports-ports/commit/d3ad9afba4a88e09ed128dc87ccb401e64bc665b#commitcomment-111141157

**Comment by mascguy** [comment]
> Imagecodecs 2023.3.16 requires libjpeg-turbo 3, which is currently in beta:
> 
> https://github.com/cgohlke/imagecodecs/blob/v2023.3.16/imagecodecs/imagecodecs.py#L164

I'm one of Marius' fellows in the MacPorts space, and the current maintainer of `libjpeg-turbo`.

As for this topic: While I can appreciate wanting to closely follow upstream projects - and prepare for breaking changes - forcing users and such down that path isn't ideal either.

Have you folks considered checking for the installed version of `libjpeg-turbo` at configure time, and adjusting things as necessary? That would certainly make things much easier, allowing use of your latest version.

**Comment by cgohlke** [comment]
> checking for the installed version of libjpeg-turbo at configure time, and adjusting things as necessary?

Cython/setuptools does not have a feasible way to do this. In fact, the intention of the release was to get rid of the libjpeg-turbo/libjpeg-turbo12/libjpeg switches. Libjpeg-turbo 3, even if in beta, has just too many features relevant for this library to ignore.

If you need to build against libjpeg-turbo 2, try to revert the relevant changes: https://github.com/conda-forge/imagecodecs-feedstock/pull/79#issuecomment-1492667986

**Comment by opoplawski** [comment]
This seems rather unfortunate.  It would be nice if there was still a libjpeg-turbo 2 compatible cython module we could fall back on.  It may be a long time before libjpeg-turbo 3 makes its way into distributions.

**Comment by cgohlke** [comment]
OK. I'll re-add the legacy source for the JPEG8 codec extension, which can be linked to libjpeg 8 and libjpeg-turbo 2.1. The next imagecodecs release is waiting for libtiff 4.5.1 and libjpeg-turbo 3.0...

**Comment by cgohlke** [comment]
It should be possible to build v2023.7.4 with libjpeg 8 or libjpeg-turbo < 3.

**Comment by Schamschula** [comment]
Looks good: https://github.com/macports/macports-ports/commit/f32ad481447e1ca1edd323afb6a07fb2c967ec93
