### ISSUE TITLE
Lossless JPEG to JXL transcoding

### ISSUE THREAD

**Issue by JJGO** [cgohlke/imagecodecs#78]
I was wondering whether there is support for lossless transcoding of JPEG images into JPEG XL, since JPEG XL natively supports this. 

Thanks!

**Comment by cgohlke** [comment]
Fixed in v2023.7.4.

**Comment by JJGO** [comment]
Great! Just confirmed I could perform the lossless transcoding with version 2023.7.4

```python
import imagecodecs
from imagecodecs import jpeg_encode, jpegxl_decode_jpeg, jpegxl_encode_jpeg, jpeg_decode

data = np.random.randint(0,255,size=(128,128,3),dtype=np.uint8)
jpeg1 = jpeg_encode(data)
jpegxl = jpegxl_encode_jpeg(jpeg1)
jpeg2 = jpegxl_decode_jpeg(jpegxl)
np.testing.assert_allclose(jpeg_decode(jpeg1), jpeg_decode(jpeg2))
```

Thank you for implementing this!

**Comment by william-silversmith** [comment]
Hi! Thanks so much for this excellent package. I seem to have created a jxl file that is unable to be transcoded. I think it is because I tried storing a 3D grayscale image as a series of animation frames in the hopes there was some 3D compression (there wasn't). Would it be possible to detect this situation and return a more informative error? 

Thanks so much!

**Comment by cgohlke** [comment]
> Would it be possible to detect this situation and return a more informative error?

The next version will raise `ValueError("can't transcode grayscale or animated JPEG XL to JPEG")`.

**Comment by william-silversmith** [comment]
Thank you!

Do you know if the inability to transcode grayscale is intrinsic to the
format or just a missing implementation detail in the reference
implementation? It seems like JPEG does have a grayscale format.

https://stackoverflow.com/questions/51008883/is-there-a-grayscale-jpg-format

**Comment by cgohlke** [comment]
According to [this comment](https://github.com/libjxl/libjxl/issues/895#issuecomment-991148244) it should be possible to transcode grayscale JPEG. 

But when trying to convert your files with `djxl`, it emits `Warning: could not decode losslessly to JPEG`

**Comment by william-silversmith** [comment]
Thank you very much for your help!
