### ISSUE TITLE
aarch64 install

### ISSUE THREAD

**Issue by 2730938958** [cgohlke/imagecodecs#84]
May I ask how I can install this library to Ubuntu_ aarch64?

**Comment by cgohlke** [comment]
I don't have the resources to support/maintain binaries for linux-aarch64. 

Either try to build from source or use [conda-forge](https://anaconda.org/conda-forge/imagecodecs/files).

See also #24 and #4.

**Comment by cgohlke** [comment]
The v2024.1.1 release includes manylinux_aarch64 wheels.
