### ISSUE TITLE
Checking for distributions (Arch in this case) should be done in a more reliable way

### ISSUE THREAD

**Issue by WildPenquin** [cgohlke/imagecodecs#92]
Hi!

[In setup.py, on line 249](https://github.com/cgohlke/imagecodecs/blob/2ddadafd413c8b035b8f6339e8ea603bb416f011/setup.py#L249C1-L249C42):

`    if 'arch' not in platform.platform():`

This does not work on many Arch installations. The kernel version reported by `platform.platform()` is really independent of the distribution.

On my system:

```
>>> platform.platform()
'Linux-6.6.9-zen1-1-zen-x86_64-with-glibc2.38'
```
Also see discussion in [AUR](https://aur.archlinux.org/packages/python-imagecodecs).

Cheers!

**Comment by WildPenquin** [comment]
I suggest using `platform.freedesktop_os_release()`. I haven't red the freedesktop standard (just found it), but something like: `platform.freedesktop_os_release()['ID']) == 'arch'` could work.

See:
- https://docs.python.org/3/library/platform.html
- https://www.freedesktop.org/software/systemd/man/latest/os-release.html

**Comment by cgohlke** [comment]
The project provides pre-compiled wheels for manylinux_aarch64 on [PyPI](https://pypi.org/project/imagecodecs/#files). AArch64 binaries are also available on conda-forge. If you must build imagecodecs form source and the default configuration does not work, provide a `customize_build` function in an importable `imagecodecs_distributor_setup` module. That allows to define which extensions are built and to modify library names, include paths, compiler options, etc.
