### ISSUE TITLE
Is there a compiled version of this?

### ISSUE THREAD

**Issue by DIESLTEK710** [cgohlke/imagecodecs#94]
Is there a compiled version of this? Looking for a lz4 / pkm decompiler for windows ...

**Comment by cgohlke** [comment]
This library includes a codec for LZ4 but not PKM.

Please add details about the PKM format, such as links to example files, the format specification, and software/libraries that can handle PKM.

See also https://github.com/bbbbbr/gimp-rom-bin/issues/4
