### ISSUE TITLE
Feature Request: Add JPEG XL Float Support

### ISSUE THREAD

**Issue by John-P** [cgohlke/imagecodecs#95]
I noticed that JPEG XL supports float32 and float16 data types. Would it be possible to add support for this?

JPEG XL Docs: https://libjxl.readthedocs.io/en/latest/api_common.html#_CPPv411JxlDataType

**Comment by cgohlke** [comment]
`float32` and `float16` are already supported by both `jpepxl_encode` and `jpegxl_decode`. Is something not working for you? There are several sample images at https://github.com/cgohlke/imagecodecs-samples.

**Comment by John-P** [comment]
I apologize - it does appear to work! I think may have been accidentally using an outdated version when I tried earlier.
