### ISSUE TITLE
Feature Request: add Jpegli codec

### ISSUE THREAD

**Issue by abionics** [cgohlke/imagecodecs#99]
Jpegli is a new codec from Google

1) [Source code](https://github.com/libjxl/libjxl/tree/main/lib/jpegli)
2) [Article on Google blog](https://opensource.googleblog.com/2024/04/introducing-jpegli-new-jpeg-coding-library.html)

**Comment by cgohlke** [comment]
Good idea. I will try to add it for the next release (no ETA).

**Comment by cgohlke** [comment]
This will have to wait until the jpegli build system produces usable, libjpeg compatible headers and libraries.

**Comment by abionics** [comment]
> This will have to wait until the jpegli build system produces usable, libjpeg compatible headers and libraries.

@cgohlke jpegli has released it in https://github.com/google/jpegli: `"This repository contains a JPEG encoder and decoder implementation that is API and ABI compatible with libjpeg62"`

**Comment by cgohlke** [comment]
There's still no release or tag and the current main branch doesn't build cleanly on my system.
